API_ID = #ENTER YOUR API IP FROM TELEGRAM API 
API_HASH = #ENTER YOUR API HASH FROM TELEGRAM API 
################################################################################

FORWARD_ID = # TELEGRAM GROUP/CHANNEL ID
FORWARD_WB = # DISCORD WEBHOOK LINK

FORWARD2_ID = # TELEGRAM GROUP/CHANNEL ID
FORWARD2_WB = # DISCORD WEBHOOK LINK

FORWARD3_ID = # TELEGRAM GROUP/CHANNEL ID
FORWARD3_WB = # DISCORD WEBHOOK LINK

##################################################################################
#ADD MORE 

#FORWARD4_ID = # TELEGRAM GROUP/CHANNEL ID
#FORWARD4_WB = # DISCORD WEBHOOK LINK
